/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import dao.ProductDAO;
import dao.ReviewDAO;
import model.Product;
import model.Review;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;

/**
 *
 * @author nenic
 */
public class DetalleProducto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetalleProducto.class.getName());

    /**
     * Creates new form AgregarProducto
     */
    private int idProducto;
    private Product productoSeleccionado;
    private User usuarioLogueado;

    public DetalleProducto(java.awt.Frame parent, boolean modal, int idProducto, User usuarioLogueado) {
        super(parent, modal);
        initComponents();

        this.idProducto = idProducto;
        this.usuarioLogueado = usuarioLogueado;

        setLocationRelativeTo(parent);

        cargarDetalleProducto();
        cargarReviews();
    }
    
    private void cargarDetalleProducto() {
        ProductDAO productDAO = new ProductDAO();

        productoSeleccionado = productDAO.getProductById(idProducto);

        if (productoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el producto.");
            this.dispose();
            return;
        }

        lblNombre.setText(productoSeleccionado.getName());
        lblMarca.setText(productoSeleccionado.getBrand());
        lblPrecio.setText(String.valueOf(productoSeleccionado.getPrice()));
        lblDescripcion.setText(productoSeleccionado.getDescription());

        if (productoSeleccionado.getCategory() != null) {
            lblCategoria.setText(productoSeleccionado.getCategory().getName());
        } else {
            lblCategoria.setText("Sin categoría");
        }
    }
    
    private void cargarReviews() {
    ReviewDAO reviewDAO = new ReviewDAO();

    List<Review> reviews = reviewDAO.obtenerReviewsPorProducto(idProducto);

    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Usuario");
    modelo.addColumn("Comentario");
    modelo.addColumn("Puntaje");

    for (Review review : reviews) {
        modelo.addRow(new Object[]{
            review.getUser() != null ? review.getUser().getUsername() : "",
            review.getComments(),
            review.getScore()
        });
    }

    tblReviews.setModel(modelo);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloNombre = new javax.swing.JLabel();
        lblTituloMarca = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblTituloPrecio = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTituloCategoria = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblTituloDescripcion = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReviews = new javax.swing.JTable();
        lblTituloReview = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblTituloProducto = new javax.swing.JLabel();
        btnAgregarReview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloNombre.setText("Nombre:");

        lblTituloMarca.setText("Marca:");

        lblNombre.setText("jLabel3");

        lblMarca.setText("jLabel4");

        lblTituloPrecio.setText("Precio:");

        lblPrecio.setText("jLabel6");

        lblTituloCategoria.setText("Categoría:");

        lblCategoria.setText("jLabel8");

        lblTituloDescripcion.setText("Descripción:");

        lblDescripcion.setText("jLabel10");

        tblReviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReviews);

        lblTituloReview.setText("Reviews");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        lblTituloProducto.setText("Detalle del producto");

        btnAgregarReview.setText("Agregar Review");
        btnAgregarReview.addActionListener(this::btnAgregarReviewActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloDescripcion)
                            .addComponent(lblTituloCategoria)
                            .addComponent(lblTituloPrecio)
                            .addComponent(lblTituloMarca)
                            .addComponent(lblTituloNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblMarca)
                            .addComponent(lblDescripcion)
                            .addComponent(lblCategoria)
                            .addComponent(lblPrecio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblTituloReview))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(lblTituloProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(504, 504, 504)
                                .addComponent(btnAgregarReview))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloProducto)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloNombre)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloMarca)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloPrecio)
                    .addComponent(lblPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCategoria)
                    .addComponent(lblCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloDescripcion)
                    .addComponent(lblDescripcion))
                .addGap(7, 7, 7)
                .addComponent(lblTituloReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnAgregarReview))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarReviewActionPerformed
        AddReview addReview = new AddReview(this, true, productoSeleccionado, usuarioLogueado);
        addReview.setVisible(true);

        cargarReviews();
    }//GEN-LAST:event_btnAgregarReviewActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        User usuarioPrueba = new User();
        usuarioPrueba.setIdUser(1);
        usuarioPrueba.setUsername("prueba");

        java.awt.EventQueue.invokeLater(() -> 
            new DetalleProducto(new javax.swing.JFrame(), true, 1, usuarioPrueba).setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarReview;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTituloCategoria;
    private javax.swing.JLabel lblTituloDescripcion;
    private javax.swing.JLabel lblTituloMarca;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloPrecio;
    private javax.swing.JLabel lblTituloProducto;
    private javax.swing.JLabel lblTituloReview;
    private javax.swing.JTable tblReviews;
    // End of variables declaration//GEN-END:variables
}
